name: dummy-ci

on:
  push:
    branches:
      - main

jobs:
  init_project:
    name: Initialize the project
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        run: echo "Initialize the project"

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
            pwd
            cd ../dummmyci
            ls -lrt
            npm install --verbose
            node --version
            npm --version
            npm list

      - name: Test
        run: npm test

      - name: Build
        run: npm run build





